# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sgaldon/sgaldon/scacchiera_final

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sgaldon/sgaldon/scacchiera_final

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sgaldon/sgaldon/scacchiera_final/CMakeFiles /home/sgaldon/sgaldon/scacchiera_final//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sgaldon/sgaldon/scacchiera_final/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Gamers

# Build rule for target.
Gamers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Gamers
.PHONY : Gamers

# fast build rule for target.
Gamers/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gamers.dir/build.make CMakeFiles/Gamers.dir/build
.PHONY : Gamers/fast

#=============================================================================
# Target rules for targets named ChessBoard

# Build rule for target.
ChessBoard: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ChessBoard
.PHONY : ChessBoard

# fast build rule for target.
ChessBoard/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChessBoard.dir/build.make CMakeFiles/ChessBoard.dir/build
.PHONY : ChessBoard/fast

#=============================================================================
# Target rules for targets named Pieces

# Build rule for target.
Pieces: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Pieces
.PHONY : Pieces

# fast build rule for target.
Pieces/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pieces.dir/build.make CMakeFiles/Pieces.dir/build
.PHONY : Pieces/fast

#=============================================================================
# Target rules for targets named replay

# Build rule for target.
replay: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 replay
.PHONY : replay

# fast build rule for target.
replay/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/build
.PHONY : replay/fast

#=============================================================================
# Target rules for targets named scacchiera

# Build rule for target.
scacchiera: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 scacchiera
.PHONY : scacchiera

# fast build rule for target.
scacchiera/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scacchiera.dir/build.make CMakeFiles/scacchiera.dir/build
.PHONY : scacchiera/fast

Gamers.o: Gamers.cpp.o
.PHONY : Gamers.o

# target to build an object file
Gamers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gamers.dir/build.make CMakeFiles/Gamers.dir/Gamers.cpp.o
.PHONY : Gamers.cpp.o

Gamers.i: Gamers.cpp.i
.PHONY : Gamers.i

# target to preprocess a source file
Gamers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gamers.dir/build.make CMakeFiles/Gamers.dir/Gamers.cpp.i
.PHONY : Gamers.cpp.i

Gamers.s: Gamers.cpp.s
.PHONY : Gamers.s

# target to generate assembly for a file
Gamers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gamers.dir/build.make CMakeFiles/Gamers.dir/Gamers.cpp.s
.PHONY : Gamers.cpp.s

Pieces.o: Pieces.cpp.o
.PHONY : Pieces.o

# target to build an object file
Pieces.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pieces.dir/build.make CMakeFiles/Pieces.dir/Pieces.cpp.o
.PHONY : Pieces.cpp.o

Pieces.i: Pieces.cpp.i
.PHONY : Pieces.i

# target to preprocess a source file
Pieces.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pieces.dir/build.make CMakeFiles/Pieces.dir/Pieces.cpp.i
.PHONY : Pieces.cpp.i

Pieces.s: Pieces.cpp.s
.PHONY : Pieces.s

# target to generate assembly for a file
Pieces.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pieces.dir/build.make CMakeFiles/Pieces.dir/Pieces.cpp.s
.PHONY : Pieces.cpp.s

chessBoard.o: chessBoard.cpp.o
.PHONY : chessBoard.o

# target to build an object file
chessBoard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChessBoard.dir/build.make CMakeFiles/ChessBoard.dir/chessBoard.cpp.o
.PHONY : chessBoard.cpp.o

chessBoard.i: chessBoard.cpp.i
.PHONY : chessBoard.i

# target to preprocess a source file
chessBoard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChessBoard.dir/build.make CMakeFiles/ChessBoard.dir/chessBoard.cpp.i
.PHONY : chessBoard.cpp.i

chessBoard.s: chessBoard.cpp.s
.PHONY : chessBoard.s

# target to generate assembly for a file
chessBoard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ChessBoard.dir/build.make CMakeFiles/ChessBoard.dir/chessBoard.cpp.s
.PHONY : chessBoard.cpp.s

replayMain.o: replayMain.cpp.o
.PHONY : replayMain.o

# target to build an object file
replayMain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/replayMain.cpp.o
.PHONY : replayMain.cpp.o

replayMain.i: replayMain.cpp.i
.PHONY : replayMain.i

# target to preprocess a source file
replayMain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/replayMain.cpp.i
.PHONY : replayMain.cpp.i

replayMain.s: replayMain.cpp.s
.PHONY : replayMain.s

# target to generate assembly for a file
replayMain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/replayMain.cpp.s
.PHONY : replayMain.cpp.s

scacchieraMain.o: scacchieraMain.cpp.o
.PHONY : scacchieraMain.o

# target to build an object file
scacchieraMain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scacchiera.dir/build.make CMakeFiles/scacchiera.dir/scacchieraMain.cpp.o
.PHONY : scacchieraMain.cpp.o

scacchieraMain.i: scacchieraMain.cpp.i
.PHONY : scacchieraMain.i

# target to preprocess a source file
scacchieraMain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scacchiera.dir/build.make CMakeFiles/scacchiera.dir/scacchieraMain.cpp.i
.PHONY : scacchieraMain.cpp.i

scacchieraMain.s: scacchieraMain.cpp.s
.PHONY : scacchieraMain.s

# target to generate assembly for a file
scacchieraMain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/scacchiera.dir/build.make CMakeFiles/scacchiera.dir/scacchieraMain.cpp.s
.PHONY : scacchieraMain.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ChessBoard"
	@echo "... Gamers"
	@echo "... Pieces"
	@echo "... replay"
	@echo "... scacchiera"
	@echo "... Gamers.o"
	@echo "... Gamers.i"
	@echo "... Gamers.s"
	@echo "... Pieces.o"
	@echo "... Pieces.i"
	@echo "... Pieces.s"
	@echo "... chessBoard.o"
	@echo "... chessBoard.i"
	@echo "... chessBoard.s"
	@echo "... replayMain.o"
	@echo "... replayMain.i"
	@echo "... replayMain.s"
	@echo "... scacchieraMain.o"
	@echo "... scacchieraMain.i"
	@echo "... scacchieraMain.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

